<?php
/**
 * Plugin Name:       Comparison of Religions
 * Plugin URI:        https://emaus.rzeszow.pl
 * Description:       Side-by-side comparison of Christian denominations displayed as a responsive accordion with CPT data.
 * Version:           1.0.0
 * Requires at least: 6.4
 * Requires PHP:      8.0
 * Author:            Lukasz Lasota
 * License:           GPL-2.0-or-later
 * Text Domain:       comparison-of-religions
 *
 * @package ComparisonOfReligions
 *
 * ARCHITECTURE OVERVIEW
 * =====================
 * This plugin stores comparison data in a Custom Post Type (comparison_topic) with
 * a custom taxonomy (comparison_category) for grouping topics into accordion panels.
 * Each post holds a repeatable 'churches' meta field: an array of {church_name, description}.
 *
 * Data model:
 *   CPT:  comparison_topic        — one post per sub-topic (e.g. "Baptism", "Holy Scripture")
 *   Tax:  comparison_category     — groups topics (e.g. "Sacraments", "God", "Eschatology")
 *   Meta: churches (post)         — [{church_name: string, description: string (HTML)}, ...]
 *   Meta: sort_order (post)       — integer, display order within a category
 *   Meta: sort_order (term)       — integer, display order of categories in the accordion
 *
 * The single Gutenberg block (comparison-accordion) renders server-side:
 *   Desktop → CSS Grid table with aligned paragraphs across churches
 *   Mobile  → stacked layout: topic heading, then each church label + its paragraphs
 *
 * Plugin structure:
 *   app/          — PHP classes (PSR-4 autoloaded, namespace ComparisonOfReligions)
 *   src/blocks/   — Gutenberg block source (JS, SCSS, render.php)
 *   build/        — Compiled block assets (generated by `npm run build`)
 *   tools/        — One-time data import/export scripts
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Plugin-wide constants available to all files.
define( 'COR_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'COR_PLUGIN_FILE', __FILE__ );
define( 'COR_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'COR_VERSION', '1.0.0' );

// PSR-4 autoloader: maps ComparisonOfReligions\Foo\Bar → app/Foo/Bar.php.
require_once COR_PLUGIN_DIR . 'app/Autoloader.php';

use ComparisonOfReligions\PostTypes\ComparisonTopic;
use ComparisonOfReligions\Taxonomies\ComparisonCategory;
use ComparisonOfReligions\Meta\ChurchesMeta;
use ComparisonOfReligions\MetaBoxes\ChurchesMetaBox;
use ComparisonOfReligions\Blocks\RegisterBlocks;
use ComparisonOfReligions\Admin\AdminColumns;

// Initialize all plugin components (each class hooks into WordPress on construction).
new ComparisonTopic();       // Registers the comparison_topic CPT.
new ComparisonCategory();    // Registers the comparison_category taxonomy.
new ChurchesMeta();          // Registers post meta (churches, sort_order) and term meta (sort_order).
new ChurchesMetaBox();       // Admin repeater meta box for editing church data per topic.
new RegisterBlocks();        // Auto-scans build/blocks/ and registers all Gutenberg blocks.
new AdminColumns();          // Adds custom columns (church count, sort order) to CPT admin list.

// Register admin submenu page under the CPT menu for data import/export.
add_action(
	'admin_menu',
	function () {
		add_submenu_page(
			'edit.php?post_type=comparison_topic',
			__( 'Import danych', 'comparison-of-religions' ),
			__( 'Import danych', 'comparison-of-religions' ),
			'manage_options',
			'cor-import',
			'cor_import_page'
		);
	}
);

/**
 * Render the admin import/export page.
 *
 * Provides three operations:
 *   1. Import from JSON file upload (categories + topics with church descriptions)
 *   2. Export current data as downloadable JSON file
 *   3. Run built-in hardcoded data import (one-time seeding)
 */
function cor_import_page(): void {
	if ( ! current_user_can( 'manage_options' ) ) {
		wp_die( esc_html__( 'Brak uprawnień.', 'comparison-of-religions' ) );
	}

	require_once COR_PLUGIN_DIR . 'tools/import-html-data.php';

	// Handle JSON export — streams a .json file download to the browser.
	if ( isset( $_POST['cor_export_json'] ) && check_admin_referer( 'cor_import_nonce' ) ) {
		$data = cor_export_comparison_data();
		$json = wp_json_encode( $data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE );

		header( 'Content-Type: application/json; charset=utf-8' );
		header( 'Content-Disposition: attachment; filename="comparison-of-religions-export.json"' );
		header( 'Content-Length: ' . strlen( $json ) );
		echo $json; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- JSON file download.
		exit;
	}

	// Handle built-in hardcoded data import (seeds the database with default comparison data).
	if ( isset( $_POST['cor_run_import'] ) && check_admin_referer( 'cor_import_nonce' ) ) {
		echo '<div class="wrap"><h1>' . esc_html__( 'Import danych', 'comparison-of-religions' ) . '</h1><pre>';
		cor_run_import();
		echo '</pre><p><strong>' . esc_html__( 'Import zakończony.', 'comparison-of-religions' ) . '</strong></p></div>';
		return;
	}

	// Handle JSON file upload — reads uploaded .json and imports categories + topics.
	if ( isset( $_POST['cor_json_import'] ) && check_admin_referer( 'cor_import_nonce' ) ) {
		echo '<div class="wrap"><h1>' . esc_html__( 'Import z JSON', 'comparison-of-religions' ) . '</h1><pre>';

		if ( empty( $_FILES['cor_json_file']['tmp_name'] ) ) {
			echo esc_html__( 'ERROR: Nie wybrano pliku.', 'comparison-of-religions' ) . "\n";
		} else {
			$tmp_file = sanitize_text_field( $_FILES['cor_json_file']['tmp_name'] );
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reading uploaded temp file.
			$raw_json = file_get_contents( $tmp_file );
			$data     = json_decode( $raw_json, true );

			if ( null === $data || ! is_array( $data ) ) {
				echo esc_html__( 'ERROR: Nieprawidłowy format JSON.', 'comparison-of-religions' ) . "\n";
			} else {
				cor_run_json_import( $data );
			}
		}

		echo '</pre><p><strong>' . esc_html__( 'Import zakończony.', 'comparison-of-religions' ) . '</strong></p></div>';
		return;
	}

	?>
	<div class="wrap">
		<h1><?php esc_html_e( 'Import / Eksport — Porównanie wyznań', 'comparison-of-religions' ); ?></h1>

		<h2><?php esc_html_e( 'Import z pliku JSON', 'comparison-of-religions' ); ?></h2>
		<p><?php esc_html_e( 'Wgraj plik .json z danymi porównania (kategorie + tematy z opisami kościołów).', 'comparison-of-religions' ); ?></p>
		<form method="post" enctype="multipart/form-data">
			<?php wp_nonce_field( 'cor_import_nonce' ); ?>
			<p>
				<input type="file" name="cor_json_file" accept=".json,application/json" />
			</p>
			<p>
				<button type="submit" name="cor_json_import" value="1" class="button button-primary">
					<?php esc_html_e( 'Importuj z JSON', 'comparison-of-religions' ); ?>
				</button>
			</p>
		</form>

		<hr />

		<h2><?php esc_html_e( 'Eksport do JSON', 'comparison-of-religions' ); ?></h2>
		<p><?php esc_html_e( 'Pobierz aktualne dane jako plik JSON (do przeniesienia na inną instancję WP).', 'comparison-of-religions' ); ?></p>
		<form method="post">
			<?php wp_nonce_field( 'cor_import_nonce' ); ?>
			<p>
				<button type="submit" name="cor_export_json" value="1" class="button button-secondary">
					<?php esc_html_e( 'Pobierz JSON', 'comparison-of-religions' ); ?>
				</button>
			</p>
		</form>

		<hr />

		<h2><?php esc_html_e( 'Import wbudowanych danych', 'comparison-of-religions' ); ?></h2>
		<p><?php esc_html_e( 'Jednorazowy import zakodowanych na stałe danych (Kościół Rzymskokatolicki vs Zielonoświątkowy).', 'comparison-of-religions' ); ?></p>
		<form method="post">
			<?php wp_nonce_field( 'cor_import_nonce' ); ?>
			<p>
				<button type="submit" name="cor_run_import" value="1" class="button button-secondary">
					<?php esc_html_e( 'Importuj dane wbudowane', 'comparison-of-religions' ); ?>
				</button>
			</p>
		</form>
	</div>
	<?php
}

/**
 * Invalidate the comparison-accordion block's transient cache.
 *
 * Called automatically when any comparison_topic post is saved or any
 * comparison_category term is created/edited/deleted. This ensures the
 * frontend always shows fresh data after content changes, without waiting
 * for the 30-minute TTL to expire.
 *
 * Uses direct DB query to bulk-delete all transients matching the prefix,
 * which is more efficient than deleting them one by one.
 */
function cor_flush_block_cache(): void {
	global $wpdb;
	$wpdb->query( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		"DELETE FROM {$wpdb->options}
		 WHERE option_name LIKE '_transient_cor_accordion_%'
		    OR option_name LIKE '_transient_timeout_cor_accordion_%'"
	);
}
add_action( 'save_post_comparison_topic', 'cor_flush_block_cache' );
add_action( 'edited_comparison_category', 'cor_flush_block_cache' );
add_action( 'created_comparison_category', 'cor_flush_block_cache' );
add_action( 'delete_comparison_category', 'cor_flush_block_cache' );

// On activation: register CPT + taxonomy early, then flush rewrite rules
// so that any REST API endpoints become immediately available.
register_activation_hook(
	__FILE__,
	function () {
		ComparisonTopic::register_post_type();
		ComparisonCategory::register_taxonomy();
		flush_rewrite_rules();
	}
);

// On deactivation: clean up rewrite rules.
register_deactivation_hook(
	__FILE__,
	function () {
		flush_rewrite_rules();
	}
);
