<?php
/**
 * Block Registration Manager — auto-discovers and registers Gutenberg blocks.
 *
 * Scans the build/blocks/ directory for subdirectories containing block.json files
 * and registers each one using register_block_type_from_metadata(). This approach
 * means you can add new blocks just by creating a new folder in src/blocks/ —
 * no manual registration code needed.
 *
 * The build/ directory is generated by @wordpress/scripts (`npm run build`).
 * Each block folder in build/ mirrors the corresponding src/ folder and contains
 * compiled JS, CSS, and a copy of block.json.
 *
 * Currently the only block is: comparison-accordion.
 *
 * @package ComparisonOfReligions
 */

declare(strict_types=1);

namespace ComparisonOfReligions\Blocks;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Automatically scans and registers all Gutenberg blocks from build/blocks/.
 * Pattern reused from the custom-block-package plugin.
 */
class RegisterBlocks {

	/**
	 * Constructor — hooks block registration to 'init'.
	 */
	public function __construct() {
		add_action( 'init', [ $this, 'register_blocks' ] );
	}

	/**
	 * Register all blocks found in build/blocks/.
	 *
	 * Skips blocks that are already registered (prevents conflicts if another
	 * plugin registers the same block name).
	 */
	public function register_blocks(): void {
		$blocks_dir    = COR_PLUGIN_DIR . 'build/blocks/';
		$block_folders = glob( $blocks_dir . '*', GLOB_ONLYDIR );

		if ( ! is_array( $block_folders ) ) {
			return;
		}

		foreach ( $block_folders as $block_folder ) {
			$block_json_path = $block_folder . '/block.json';

			if ( ! file_exists( $block_json_path ) ) {
				continue;
			}

			$block_metadata = wp_json_file_decode( $block_json_path, [ 'associative' => true ] );
			if ( ! is_array( $block_metadata ) ) {
				continue;
			}
			$block_name = $block_metadata['name'] ?? null;

			if ( ! $block_metadata || ! $block_name ) {
				continue;
			}

			if ( \WP_Block_Type_Registry::get_instance()->is_registered( $block_name ) ) {
				continue;
			}

			register_block_type_from_metadata( $block_json_path );
		}
	}
}
